apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          # - name: arr-stack
          # - name: blackbox-exporter
          #   namespace: monitoring
          - name: calibre-web
            project: media-project
          - name: cert-manager
            project: network-project
          # - name: cloudnative-pg
          #   project: db-project
          #   serverSideApply: true
          - name: convertx
            project: utilities-project
          # - name: crowdsec
          - name: pihole
            project: network-project
          - name: traefik
            project: network-project
          # - name: external-dns
          #   project: network-project
          - name: external-secrets
            project: system-project
          # - name: go-healthcheck
          # - name: home-assistant
          - name: homepage
            project: utilities-project
          # - name: httpbin
          # - name: immich
          - name: jellyfin
            project: media-project
          - name: it-tools
            project: utilities-project
          # - name: ingres
          - name: kube-prometheus-stack
            namespace: monitoring
            project: monitoring-project
            serverSideApply: true
          - name: loki
            project: monitoring-project
          # - name: longhorn
          #   namespace: longhorn-system
          #   serverSideApply: true
          #   serverSideDiff: true
          # - name: mealie
          - name: metallb
            project: network-project
          # - name: mosquitto
          # - name: nextcloud
          - name: oauth2-proxy
            project: security-project
          # - name: opencloud
          # - name: opentelemetry-collector
          # - name: opentelemetry-operator
          # - name: paperless-ngx
          #   project: media-project
          - name: reloader
            project: system-project
          # - name: satisfactory-server
          # - name: snapshot-controller
          # - name: tailscale-operator
          # - name: vaultwarden
          # - name: velero
          # - name: zigbee2mqtt

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
        argocd.argoproj.io/compare-options: '{{ printf "%s=%s" "ServerSideDiff" (dig "serverSideDiff" "false" . | toString) }}'
    spec:
      project: '{{ dig "project" "default" . }}'
      source:
        repoURL: https://github.com/ssongin/helm_packages.git
        targetRevision: HEAD
        path: "k8s-apps/{{ .name }}"
      destination:
        name: in-cluster
        namespace: '{{ default .name (dig "namespace" "" .) }}'
      ignoreDifferences:
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jqPathExpressions:
            - .spec.conversion.webhook.clientConfig.caBundle
        # FIXME: https://github.com/cloudnative-pg/charts/issues/426
        - group: postgresql.cnpg.io
          kind: Cluster
          jqPathExpressions:
            - .spec.postgresql.pg_hba
            - .spec.postgresql.pg_ident
        - group: apps
          kind: "*"
          jqPathExpressions:
            - .spec.template.spec.hostUsers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - '{{ printf "%s=%s" "ServerSideApply" (dig "serverSideApply" "false" . | toString) }}'
