apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: git-helm-repos
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: git-helm-repos
  source:
    repoURL: git@github.com:ssongin/argocd.git
    path: argocd-config/
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
